/**
 * The HTTP client.
 *
 * Small on purpose — it exists so that failures arrive as `CliError`s with the
 * right exit code and a usable message, instead of as `TypeError: fetch
 * failed`, which is what an unwrapped `fetch` gives a user whose wifi dropped.
 */

import {
  AuthError,
  CliError,
  ConflictError,
  InterruptedError,
  NetworkError,
  NotFoundError,
  type CliErrorOptions,
} from './errors.ts';

export const DEFAULT_TIMEOUT_MS = 30_000;

export interface HttpClientOptions {
  baseUrl: string;
  fetch: typeof globalThis.fetch;
  token?: string | undefined;
  userAgent: string;
  timeoutMs?: number;
  /** Aborted on Ctrl-C, so a long request unwinds with the rest of the command. */
  signal?: AbortSignal | undefined;
}

export interface RequestOptions {
  query?: Record<string, string | number | boolean | undefined>;
  /**
   * JSON-serialized, unless it is a `FormData` — then it is passed through
   * untouched and the content-type header is left alone, because the
   * multipart boundary is generated by the runtime and only it knows the
   * value. Setting `content-type` yourself for a multipart body produces a
   * request the server cannot parse.
   */
  body?: unknown;
  headers?: Record<string, string>;
  /** Send no `Authorization` header even when a token is configured. */
  anonymous?: boolean;
  timeoutMs?: number;
  signal?: AbortSignal;
}

/**
 * Flatten the several shapes an API may use for an error into one string.
 *
 * Rails alone produces `{error: "..."}`, `{errors: ["...", ...]}` and
 * `{errors: {field: ["msg"]}}` depending on which controller failed; OAuth
 * endpoints use `{error, error_description}`. A client that understands only
 * one of them shows "[object Object]" for the rest.
 */
export const formatApiError = (payload: unknown, status: number): string => {
  if (typeof payload === 'string' && payload.trim() !== '') return payload.trim();

  if (typeof payload === 'object' && payload !== null) {
    const record = payload as Record<string, unknown>;

    const description = record['error_description'];
    if (typeof description === 'string') return description;

    const single = record['error'];
    if (typeof single === 'string') return single;

    const many = record['errors'];
    if (Array.isArray(many)) return many.map(String).join('; ');
    if (typeof many === 'object' && many !== null) {
      return Object.entries(many as Record<string, unknown>)
        .map(([field, messages]) =>
          `${field} ${Array.isArray(messages) ? messages.map(String).join(', ') : String(messages)}`,
        )
        .join('; ');
    }

    const message = record['message'];
    if (typeof message === 'string') return message;
  }

  return `The server returned HTTP ${status}.`;
};

const errorForStatus = (status: number, message: string, options: CliErrorOptions): CliError => {
  if (status === 401) {
    return new AuthError('auth.rejected', message, {
      hint: 'Run `login` to sign in again.',
      ...options,
    });
  }
  if (status === 403) return new AuthError('auth.forbidden', message, options);
  if (status === 404) return new NotFoundError('not_found', message, options);
  if (status === 409 || status === 422) return new ConflictError('conflict', message, options);
  if (status === 429) {
    return new NetworkError('rate_limited', message, {
      hint: 'Wait a moment and try again.',
      ...options,
    });
  }
  if (status >= 500) {
    return new NetworkError('server_error', message, {
      hint: 'This is a problem on the server. Try again shortly.',
      ...options,
    });
  }
  return new CliError('request_failed', message, options);
};

/** Turn a transport-level failure into something a human can act on. */
const errorForTransport = (error: unknown, baseUrl: string, timedOut: boolean): CliError => {
  const named = error as { name?: string; code?: string; cause?: { code?: string } };
  const code = named.code ?? named.cause?.code;

  if (named.name === 'TimeoutError' || named.name === 'AbortError') {
    // Ctrl-C and a lapsed deadline both arrive here as an abort, and only the
    // timeout signal's own state tells them apart. Reporting a cancellation as
    // a timeout prints a network failure the user did not have and exits 5
    // where every script expects 130.
    if (!timedOut) return new InterruptedError();

    return new NetworkError('timeout', `Request to ${baseUrl} timed out.`, {
      hint: 'Check your connection, or try again.',
      cause: error,
    });
  }
  if (code === 'ENOTFOUND' || code === 'EAI_AGAIN') {
    return new NetworkError('dns', `Could not resolve ${baseUrl}.`, {
      hint: 'Check the endpoint address and your DNS.',
      cause: error,
    });
  }
  if (code === 'ECONNREFUSED') {
    return new NetworkError('refused', `Could not connect to ${baseUrl}.`, {
      hint: 'Check that the endpoint is correct and reachable.',
      cause: error,
    });
  }
  if (code === 'CERT_HAS_EXPIRED' || code === 'UNABLE_TO_VERIFY_LEAF_SIGNATURE') {
    return new NetworkError('tls', `The TLS certificate for ${baseUrl} could not be verified.`, {
      cause: error,
    });
  }
  return new NetworkError('network', `Request to ${baseUrl} failed.`, { cause: error });
};

export class HttpClient {
  private options: HttpClientOptions;

  constructor(options: HttpClientOptions) {
    this.options = options;
  }

  get baseUrl(): string {
    return this.options.baseUrl;
  }

  async request<T = unknown>(
    method: string,
    path: string,
    options: RequestOptions = {},
  ): Promise<T> {
    const url = new URL(path, this.options.baseUrl);
    for (const [key, value] of Object.entries(options.query ?? {})) {
      // URLSearchParams handles the encoding, which is the bug in our other
      // CLI: it concatenates `?status=${value}` and sends spaces raw.
      if (value !== undefined) url.searchParams.set(key, String(value));
    }

    const headers: Record<string, string> = {
      accept: 'application/json',
      'user-agent': this.options.userAgent,
      ...options.headers,
    };

    if (options.anonymous !== true && this.options.token !== undefined) {
      headers['authorization'] = `Bearer ${this.options.token}`;
    }

    let body: string | FormData | undefined;
    if (options.body instanceof FormData) {
      body = options.body;
    } else if (options.body !== undefined) {
      body = JSON.stringify(options.body);
      headers['content-type'] = 'application/json';
    }

    const timeout = AbortSignal.timeout(options.timeoutMs ?? this.options.timeoutMs ?? DEFAULT_TIMEOUT_MS);
    const signals = [timeout, options.signal, this.options.signal].filter(
      (signal): signal is AbortSignal => signal !== undefined,
    );

    let response: Response;
    try {
      response = await this.options.fetch(url, {
        method,
        headers,
        ...(body === undefined ? {} : { body }),
        signal: signals.length === 1 ? signals[0] : AbortSignal.any(signals),
      });
    } catch (error) {
      throw errorForTransport(error, this.options.baseUrl, timeout.aborted);
    }

    // Reading the body is still the transport, and it is where a stall, a
    // dropped connection, or a Ctrl-C after the headers arrived actually
    // lands — fetch has already resolved by then. Outside this try it
    // escaped as an unclassified error and exited 1.
    let text: string;
    try {
      text = await response.text();
    } catch (error) {
      throw errorForTransport(error, this.options.baseUrl, timeout.aborted);
    }

    let payload: unknown = undefined;
    if (text !== '') {
      try {
        payload = JSON.parse(text);
      } catch {
        payload = text;
      }
    }

    if (!response.ok) {
      throw errorForStatus(response.status, formatApiError(payload, response.status), {
        details: { status: response.status, url: url.toString() },
      });
    }

    return payload as T;
  }

  get<T = unknown>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>('GET', path, options);
  }

  put<T = unknown>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>('PUT', path, options);
  }

  post<T = unknown>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>('POST', path, options);
  }

  delete<T = unknown>(path: string, options?: RequestOptions): Promise<T> {
    return this.request<T>('DELETE', path, options);
  }
}
