import assert from 'node:assert/strict';
import { test } from 'node:test';

import { AuthError, ConflictError, NetworkError, NotFoundError } from '../../src/kit/errors.ts';
import { formatApiError, HttpClient } from '../../src/kit/http.ts';

const client = (handler: typeof globalThis.fetch): HttpClient =>
  new HttpClient({ baseUrl: 'https://api.example.test', fetch: handler, userAgent: 'test/1.0' });

const json = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });

test('flattens every error shape an API might use', () => {
  // Rails alone produces three of these depending on which controller failed.
  assert.equal(formatApiError({ error: 'Nope.' }, 400), 'Nope.');
  assert.equal(formatApiError({ errors: ['a', 'b'] }, 400), 'a; b');
  assert.equal(formatApiError({ errors: { title: ["can't be blank"] } }, 422), "title can't be blank");
  assert.equal(formatApiError({ error_description: 'PKCE failed.' }, 400), 'PKCE failed.');
  assert.equal(formatApiError({}, 503), 'The server returned HTTP 503.');
});

test('maps status codes to distinct error types', async () => {
  const cases: [number, unknown][] = [
    [401, AuthError],
    [403, AuthError],
    [404, NotFoundError],
    [422, ConflictError],
    [500, NetworkError],
  ];
  for (const [status, type] of cases) {
    await assert.rejects(
      client(async () => json({ error: 'x' }, status)).get('/thing'),
      (error: unknown) => error instanceof (type as new () => Error),
      `status ${status}`,
    );
  }
});

test('encodes query parameters and drops undefined ones', async () => {
  let seen = '';
  await client(async (input) => {
    seen = String(input);
    return json({ ok: true });
  }).get('/posts', { query: { status: 'draft published', limit: 10, missing: undefined } });

  // Concatenating this by hand is the bug in our other CLI: it sends the
  // space raw.
  assert.match(seen, /status=draft\+published/);
  assert.match(seen, /limit=10/);
  assert.doesNotMatch(seen, /missing/);
});

test('a FormData body is passed through without a content-type header', async () => {
  // The multipart boundary is generated by the runtime; setting content-type
  // ourselves produces a request the server cannot parse.
  let contentType: string | null = 'unset';
  let sentBody: unknown;

  const form = new FormData();
  form.append('file', new Blob(['x'], { type: 'image/png' }), 'a.png');

  await client(async (_input, init) => {
    contentType = new Headers(init?.headers).get('content-type');
    sentBody = init?.body;
    return json({ url: 'https://cdn.example/a.png' });
  }).post('/uploads', { body: form });

  assert.equal(contentType, null);
  assert.ok(sentBody instanceof FormData);
});

test('a JSON body is serialized and typed', async () => {
  let contentType: string | null = null;
  let sentBody: unknown;
  await client(async (_input, init) => {
    contentType = new Headers(init?.headers).get('content-type');
    sentBody = init?.body;
    return json({ ok: true });
  }).post('/posts', { body: { post: { title: 'Hi' } } });

  assert.equal(contentType, 'application/json');
  assert.equal(sentBody, '{"post":{"title":"Hi"}}');
});

test('a transport failure becomes a network error, not a raw TypeError', async () => {
  await assert.rejects(
    client(() => Promise.reject(Object.assign(new Error('boom'), { code: 'ECONNREFUSED' }))).get('/x'),
    (error: unknown) => error instanceof NetworkError && /Could not connect/.test((error as Error).message),
  );
});

test('anonymous requests omit the Authorization header', async () => {
  let auth: string | null = 'unset';
  const authed = new HttpClient({
    baseUrl: 'https://api.example.test',
    fetch: async (_input, init) => {
      auth = new Headers(init?.headers).get('authorization');
      return json({ ok: true });
    },
    userAgent: 'test/1.0',
    token: 'tok_1',
  });

  await authed.get('/a');
  assert.equal(auth, 'Bearer tok_1');
  await authed.get('/b', { anonymous: true });
  assert.equal(auth, null);
});
