import assert from 'node:assert/strict';
import { test } from 'node:test';

import {
  AuthError,
  ConflictError,
  EXIT,
  InterruptedError,
  NetworkError,
  NotFoundError,
} from '../../src/kit/errors.ts';
import { formatApiError, HttpClient } from '../../src/kit/http.ts';

const client = (handler: typeof globalThis.fetch): HttpClient =>
  new HttpClient({ baseUrl: 'https://api.example.test', fetch: handler, userAgent: 'test/1.0' });

const json = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });

test('flattens every error shape an API might use', () => {
  // Rails alone produces three of these depending on which controller failed.
  assert.equal(formatApiError({ error: 'Nope.' }, 400), 'Nope.');
  assert.equal(formatApiError({ errors: ['a', 'b'] }, 400), 'a; b');
  assert.equal(formatApiError({ errors: { title: ["can't be blank"] } }, 422), "title can't be blank");
  assert.equal(formatApiError({ error_description: 'PKCE failed.' }, 400), 'PKCE failed.');
  assert.equal(formatApiError({}, 503), 'The server returned HTTP 503.');
});

test('maps status codes to distinct error types', async () => {
  const cases: [number, unknown][] = [
    [401, AuthError],
    [403, AuthError],
    [404, NotFoundError],
    [422, ConflictError],
    [500, NetworkError],
  ];
  for (const [status, type] of cases) {
    await assert.rejects(
      client(async () => json({ error: 'x' }, status)).get('/thing'),
      (error: unknown) => error instanceof (type as new () => Error),
      `status ${status}`,
    );
  }
});

test('encodes query parameters and drops undefined ones', async () => {
  let seen = '';
  await client(async (input) => {
    seen = String(input);
    return json({ ok: true });
  }).get('/posts', { query: { status: 'draft published', limit: 10, missing: undefined } });

  // Concatenating this by hand is the bug in our other CLI: it sends the
  // space raw.
  assert.match(seen, /status=draft\+published/);
  assert.match(seen, /limit=10/);
  assert.doesNotMatch(seen, /missing/);
});

test('a FormData body is passed through without a content-type header', async () => {
  // The multipart boundary is generated by the runtime; setting content-type
  // ourselves produces a request the server cannot parse.
  let contentType: string | null = 'unset';
  let sentBody: unknown;

  const form = new FormData();
  form.append('file', new Blob(['x'], { type: 'image/png' }), 'a.png');

  await client(async (_input, init) => {
    contentType = new Headers(init?.headers).get('content-type');
    sentBody = init?.body;
    return json({ url: 'https://cdn.example/a.png' });
  }).post('/uploads', { body: form });

  assert.equal(contentType, null);
  assert.ok(sentBody instanceof FormData);
});

test('a JSON body is serialized and typed', async () => {
  let contentType: string | null = null;
  let sentBody: unknown;
  await client(async (_input, init) => {
    contentType = new Headers(init?.headers).get('content-type');
    sentBody = init?.body;
    return json({ ok: true });
  }).post('/posts', { body: { post: { title: 'Hi' } } });

  assert.equal(contentType, 'application/json');
  assert.equal(sentBody, '{"post":{"title":"Hi"}}');
});

test('a transport failure becomes a network error, not a raw TypeError', async () => {
  await assert.rejects(
    client(() => Promise.reject(Object.assign(new Error('boom'), { code: 'ECONNREFUSED' }))).get('/x'),
    (error: unknown) => error instanceof NetworkError && /Could not connect/.test((error as Error).message),
  );
});

test('anonymous requests omit the Authorization header', async () => {
  let auth: string | null = 'unset';
  const authed = new HttpClient({
    baseUrl: 'https://api.example.test',
    fetch: async (_input, init) => {
      auth = new Headers(init?.headers).get('authorization');
      return json({ ok: true });
    },
    userAgent: 'test/1.0',
    token: 'tok_1',
  });

  await authed.get('/a');
  assert.equal(auth, 'Bearer tok_1');
  await authed.get('/b', { anonymous: true });
  assert.equal(auth, null);
});

test("a caller's abort is a cancellation, not a timeout", async () => {
  // Ctrl-C reaches fetch as an AbortError, the same shape a lapsed deadline
  // produces. Reporting it as a timeout prints a network failure that did not
  // happen and exits 5 where every script checks for 130.
  const controller = new AbortController();
  const client = new HttpClient({
    baseUrl: 'https://api.example.test',
    fetch: (_input, init) =>
      new Promise((_resolve, reject) => {
        init?.signal?.addEventListener('abort', () => {
          reject(Object.assign(new Error('aborted'), { name: 'AbortError' }));
        });
      }),
    userAgent: 'test/1.0',
    signal: controller.signal,
  });

  const pending = client.get('/slow');
  controller.abort();

  await assert.rejects(pending, (error: unknown) => {
    assert.ok(error instanceof InterruptedError, `got ${String(error)}`);
    assert.equal((error as InterruptedError).exitCode, EXIT.interrupted);
    return true;
  });
});

test('a lapsed deadline is still a timeout', async () => {
  // The other half: without it, the fix above could just relabel every abort.
  const client = new HttpClient({
    baseUrl: 'https://api.example.test',
    fetch: (_input, init) =>
      new Promise((_resolve, reject) => {
        // A referenced timer stands in for the open socket a real request
        // holds. AbortSignal.timeout's own timer is unref'd, so without one
        // the process exits before the deadline it is waiting for.
        const holdOpen = setTimeout(() => reject(new Error('never aborted')), 5_000);
        init?.signal?.addEventListener('abort', () => {
          clearTimeout(holdOpen);
          reject(init.signal?.reason);
        });
      }),
    userAgent: 'test/1.0',
    timeoutMs: 5,
  });

  await assert.rejects(client.get('/slow'), (error: unknown) => {
    assert.ok(error instanceof NetworkError, `got ${String(error)}`);
    assert.equal((error as NetworkError).code, 'timeout');
    return true;
  });
});

test('a failure while reading the body is still classified as transport', async () => {
  // fetch() resolves once the headers arrive, so a stall or a dropped
  // connection lands on response.text() instead. Outside the transport catch
  // it escaped as an unclassified error and exited 1.
  const client = new HttpClient({
    baseUrl: 'https://api.example.test',
    fetch: async () =>
      new Response(
        new ReadableStream({
          pull() {
            throw Object.assign(new Error('connection reset'), { code: 'ECONNRESET' });
          },
        }),
      ),
    userAgent: 'test/1.0',
  });

  await assert.rejects(client.get('/thing'), (error: unknown) => {
    assert.ok(error instanceof NetworkError, `got ${String(error)}`);
    assert.equal((error as NetworkError).exitCode, EXIT.network);
    return true;
  });
});

test('a cancellation while reading the body is a cancellation', async () => {
  // The same path, but the user pressed Ctrl-C after the headers arrived.
  const controller = new AbortController();
  const client = new HttpClient({
    baseUrl: 'https://api.example.test',
    fetch: async () =>
      new Response(
        new ReadableStream({
          pull() {
            controller.abort();
            throw Object.assign(new Error('aborted'), { name: 'AbortError' });
          },
        }),
      ),
    userAgent: 'test/1.0',
    signal: controller.signal,
  });

  await assert.rejects(client.get('/thing'), (error: unknown) => {
    assert.ok(error instanceof InterruptedError, `got ${String(error)}`);
    return true;
  });
});
