/**
 * Shell completion scripts, generated from the command registry.
 *
 * The same property that makes help un-driftable makes these un-driftable: the
 * registry is the only source, so a command that exists is completable and a
 * flag that exists is offered. Most CLIs hand-write a `_mycli` script that is
 * accurate on the day it is committed and wrong two releases later.
 *
 * These are **static** scripts. They list what the binary knew at the moment
 * they were generated rather than calling back into it on every keystroke,
 * which keeps completion instant and works when the binary is slow to start.
 * Told to `eval "$(acme completions zsh)"` from a shell rc, they are
 * regenerated on every new shell and cannot go stale in practice.
 *
 * What they deliberately do not do is complete *values* fetched from a server —
 * post ids, project names. That needs a callback, a cache, and a story for what
 * happens when you are offline or signed out, and it is not free enough to
 * include by default. `choices` on a flag is completed, because the registry
 * already knows it.
 */

import type { CommandDef, FlagDef, ProgramDef } from './command.ts';

export const SHELLS = ['bash', 'zsh', 'fish'] as const;
export type Shell = (typeof SHELLS)[number];

const visible = <T extends { hidden?: boolean }>(items: readonly T[]): T[] =>
  items.filter((item) => item.hidden !== true);

const visibleFlags = (flags: Record<string, FlagDef> = {}): [string, FlagDef][] =>
  Object.entries(flags).filter(([, flag]) => flag.hidden !== true);

/** Every name a command answers to. */
const names = (command: CommandDef): string[] => [command.name, ...(command.aliases ?? [])];

/**
 * A command and the path of words that reaches it.
 *
 * Flattened rather than recursed at render time so each shell's generator is a
 * loop over a list instead of its own tree walk — three tree walks is three
 * places for subcommands to be handled subtly differently.
 */
export interface CompletionEntry {
  /** `['notes']`, `['config', 'set']` — primary names only, no aliases. */
  path: string[];
  command: CommandDef;
}

export const walk = (commands: readonly CommandDef[], prefix: string[] = []): CompletionEntry[] =>
  visible(commands).flatMap((command) => {
    const path = [...prefix, command.name];
    return [{ path, command }, ...walk(command.subcommands ?? [], path)];
  });

/**
 * Single-quote for POSIX shells and fish alike.
 *
 * Inside single quotes every character is literal, so the only thing needing
 * care is a single quote itself: close, emit an escaped one, reopen.
 */
const sq = (value: string): string => `'${value.replaceAll("'", `'\\''`)}'`;

/**
 * Collapse a summary to one line of plain text.
 *
 * Summaries are prose written for help output. A newline would end the
 * statement it is embedded in, and backticks are a command substitution in
 * double-quoted contexts — neither is worth risking for the sake of preserving
 * formatting nobody sees in a completion menu.
 */
const oneLine = (value: string): string => value.replace(/\s+/g, ' ').replaceAll('`', "'").trim();

/**
 * zsh's `_describe` takes `value:description` pairs, so a colon inside the
 * description silently truncates it — or worse, shifts everything after it into
 * the wrong field. Summaries contain colons ("note: …", ratios, times), so this
 * is not hypothetical.
 */
const zshDescribe = (value: string, description: string): string =>
  sq(`${value}:${oneLine(description).replaceAll(':', '\\:')}`);

const flagSpellings = (name: string, flag: FlagDef): string[] =>
  flag.short === undefined ? [`--${name}`] : [`--${name}`, `-${flag.short}`];

/* -------------------------------------------------------------------------- */

/**
 * A real command name to use in the generated script's comments.
 *
 * Hardcoding one means every adopter's completion file explains itself with a
 * command their CLI does not have — the template's example leaking downstream.
 */
const exampleCommand = (program: ProgramDef): string =>
  visible(program.commands)[0]?.name ?? '<command>';

export const bashCompletions = (program: ProgramDef): string => {
  const entries = walk(program.commands);
  const fn = `_${program.name.replaceAll(/[^A-Za-z0-9]/g, '_')}`;
  const example = exampleCommand(program);

  const cases = entries.map((entry) => {
    const subcommands = visible(entry.command.subcommands ?? []).map((c) => c.name);
    const flags = visibleFlags(entry.command.flags).flatMap(([n, f]) => flagSpellings(n, f));
    return `    ${sq(entry.path.join(' '))}) words=${sq([...subcommands, ...flags].join(' '))} ;;`;
  });

  const roots = visible(program.commands).flatMap(names);
  const globals = visibleFlags(program.globalFlags).flatMap(([n, f]) => flagSpellings(n, f));

  return `# bash completion for ${program.name}
# Generated by \`${program.name} completions bash\` — do not edit.
# Install:  ${program.name} completions bash > /etc/bash_completion.d/${program.name}
#     or:   eval "$(${program.name} completions bash)"   # in ~/.bashrc

${fn}() {
  local cur prev line words
  cur="\${COMP_WORDS[COMP_CWORD]}"

  # The command path typed so far, ignoring flags and their values, so that
  # \`${program.name} --verbose ${example} <TAB>\` resolves the same as \`${program.name} ${example} <TAB>\`.
  line=""
  local i
  for (( i=1; i < COMP_CWORD; i++ )); do
    case "\${COMP_WORDS[i]}" in
      -*) ;;
      *) line="\${line:+\$line }\${COMP_WORDS[i]}" ;;
    esac
  done

  case "\$line" in
${cases.join('\n')}
    *) words=${sq(roots.join(' '))} ;;
  esac

  COMPREPLY=( \$(compgen -W "\$words ${globals.join(' ')}" -- "\$cur") )
  return 0
}

complete -F ${fn} ${program.name}
`;
};

/* -------------------------------------------------------------------------- */

export const zshCompletions = (program: ProgramDef): string => {
  const entries = walk(program.commands);
  const fn = `_${program.name.replaceAll(/[^A-Za-z0-9]/g, '_')}`;
  const example = exampleCommand(program);

  const cases = entries.map((entry) => {
    const subcommands = visible(entry.command.subcommands ?? []).map((c) =>
      zshDescribe(c.name, c.summary),
    );
    const flags = visibleFlags(entry.command.flags).flatMap(([n, f]) =>
      flagSpellings(n, f).map((spelling) => zshDescribe(spelling, f.summary)),
    );
    return `      ${sq(entry.path.join(' '))}) offer=(${[...subcommands, ...flags].join(' ')}) ;;`;
  });

  const roots = visible(program.commands).flatMap((c) =>
    names(c).map((name) => zshDescribe(name, c.summary)),
  );
  const globals = visibleFlags(program.globalFlags).flatMap(([n, f]) =>
    flagSpellings(n, f).map((spelling) => zshDescribe(spelling, f.summary)),
  );

  return `#compdef ${program.name}
# zsh completion for ${program.name}
# Generated by \`${program.name} completions zsh\` — do not edit.
# Install:  ${program.name} completions zsh > "\${fpath[1]}/_${program.name}"
#     or:   eval "$(${program.name} completions zsh)"   # in ~/.zshrc

${fn}() {
  local -a path_words offer
  local i

  # The command path typed so far, flags dropped, so that
  # \`${program.name} --verbose ${example} <TAB>\` resolves the same as \`${program.name} ${example} <TAB>\`.
  for (( i = 2; i < CURRENT; i++ )); do
    [[ "\${words[i]}" == -* ]] && continue
    path_words+=("\${words[i]}")
  done

  case "\${(j: :)path_words}" in
${cases.join('\n')}
      *) offer=(${roots.join(' ')}) ;;
  esac

  offer+=(${globals.join(' ')})
  _describe -t ${program.name} ${sq(program.name)} offer
}

# Autoloaded from fpath, the file body *is* the function and zsh calls it.
# Sourced or eval'd from an rc file, it is not — so register it by hand.
if [[ "\$funcstack[1]" == "${fn}" ]]; then
  ${fn} "\$@"
else
  compdef ${fn} ${program.name}
fi
`;
};

/* -------------------------------------------------------------------------- */

export const fishCompletions = (program: ProgramDef): string => {
  const lines: string[] = [
    `# fish completion for ${program.name}`,
    `# Generated by \`${program.name} completions fish\` — do not edit.`,
    `# Install:  ${program.name} completions fish > ~/.config/fish/completions/${program.name}.fish`,
    '',
    '# Disable file completion by default; commands opt back in where it makes sense.',
    `complete -c ${program.name} -f`,
    '',
  ];

  for (const entry of walk(program.commands)) {
    // fish matches on the sequence of non-flag words, which is exactly the
    // condition helper below — no manual position arithmetic.
    const condition =
      entry.path.length === 1
        ? '__fish_use_subcommand'
        : `__fish_seen_subcommand_from ${entry.path[entry.path.length - 2]}`;

    for (const name of names(entry.command)) {
      lines.push(
        `complete -c ${program.name} -n ${sq(condition)} -a ${sq(name)} -d ${sq(oneLine(entry.command.summary))}`,
      );
    }

    for (const [name, flag] of visibleFlags(entry.command.flags)) {
      const parts = [
        `complete -c ${program.name}`,
        `-n ${sq(`__fish_seen_subcommand_from ${entry.command.name}`)}`,
        `-l ${sq(name)}`,
        ...(flag.short === undefined ? [] : [`-s ${sq(flag.short)}`]),
        // -x is -r plus "no files". A flag with a fixed set of values wants
        // only those; one without (--config, --token) still wants the file
        // list, so it stays -r.
        ...(flag.type === 'string' ? [flag.choices === undefined ? '-r' : '-x'] : []),
        ...(flag.choices === undefined ? [] : [`-a ${sq(flag.choices.join(' '))}`]),
        `-d ${sq(oneLine(flag.summary))}`,
      ];
      lines.push(parts.join(' '));
    }
  }

  lines.push('');
  for (const [name, flag] of visibleFlags(program.globalFlags)) {
    const parts = [
      `complete -c ${program.name}`,
      `-l ${sq(name)}`,
      ...(flag.short === undefined ? [] : [`-s ${sq(flag.short)}`]),
      ...(flag.type === 'string' ? ['-r'] : []),
      `-d ${sq(oneLine(flag.summary))}`,
    ];
    lines.push(parts.join(' '));
  }

  return `${lines.join('\n')}\n`;
};

export const completionsFor = (program: ProgramDef, shell: Shell): string => {
  if (shell === 'bash') return bashCompletions(program);
  if (shell === 'zsh') return zshCompletions(program);
  return fishCompletions(program);
};
